version: '3.8'
name: "vrs-project"
services:
  db:
    image: postgres
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_vrs_data:/var/lib/postgresql/data
  backend:
    build:
      context: ../../../../dev/projekt-vrs
      dockerfile: .Dockerfile-backend
    env_file: .env
    ports:
      - '8080:8080'
    depends_on:
      - db
  frontend:
    build:
      context: ../../../../dev/projekt-vrs
      dockerfile: .Dockerfile-frontend
    ports:
      - '4200:80'
    depends_on:
      - backend
  adminer:
    image: adminer
    ports:
      - '8081:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres_vrs_data: